### ISSUE TITLE
Be able to add users to a private task without them logging in first

### ISSUE THREAD

**Issue by wonderchook** [hotosm/osm-tasking-manager#10]
Right now the user accounts require you to login to OpenStreetmap before you show up to the admin.

There should be a way to add people based on their username ahead of time.

**Comment by pgiraud** [comment]
You should now be able to do that by first adding a user in the list of users (http://tasks.hotosm.org/users), then you can add the newly added user to the whitelist of the job (http://tasks.hotosm.org/job/4/users).
Does it help?
