### ISSUE TITLE
Prevent user from splitting too much

### ISSUE THREAD

**Issue by pgiraud** [hotosm/osm-tasking-manager#105]
From Pierre Béland : 
C'est avec l'expérience que nous allons voir les problèmes éventuels et solutions pour améliorer l'API.
voir http://tasks.hotosm.org/job/97

Quelqu'un a sub-sub-subdivisé des tâches dans une zone rurale sans même en sélectionner une. Ou il s'amuse, ou il ne sais pas ce qu'il fait.

En temps que créateur de la tâche, je n'ai aucune possibilité de corriger. Je ne sais pas non plus qui en est responsable.

**Comment by pgiraud** [comment]
One solution would be to prevent users from splitting more than twice.

**Comment by pierzen** [comment]
I would be more drastic and accept only once. This already split the task by 4. To mulitiply by 16 may be excessive. At this point, the editor of the task should redo it.

 
Pierre

**Comment by pgiraud** [comment]
Implemented in the `workflow` branch.
