### ISSUE TITLE
Assure Job integrity of the Tasking Manager jobs

### ISSUE THREAD

**Issue by pierzen** [hotosm/osm-tasking-manager#111]
Tasks are deleted by other people then the administrator who created this job. No backup lets recuperate this job and the status of each micro-task.  This creates coordination problems for activations going on. 

A backup of jobs should be implemented.  Only the super-administrator and the administrator who created a  task  should have the ability to delete the task. Others may only archive it. A log should be kept of such actions.

Presently, we can click on the delete button instead of the edit. And there is no possibility to revert this.

An other option would be to replace the Delete option by a Unview option. This way, the job would only be removed from the list of tasks that are showed in the Task Manager. It would be easy to revert this option.

**Comment by pgiraud** [comment]
Jobs cannot be deleted any more. They can at most be archived which can be reverted.
Closing.
