### ISSUE TITLE
Hi ?

### ISSUE THREAD

**Issue by desirendihokubwayo** [hotosm/osm-tasking-manager#119]
A news contributor on Openstreetmap in Burundi to Bujumbura town

**Comment by pgiraud** [comment]
Closing this as it doesn't seem like a valid issue.

**Comment by desirendihokubwayo** [comment]
ok comment on trouve si on a perdu le password

**Comment by pgiraud** [comment]
De quel "password" parlez-vous ?

On Tue, Feb 19, 2013 at 9:31 AM, desirendihokubwayo <
notifications@github.com> wrote:

> ok comment on trouve si on a perdu le password
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hotosm/osm-tasking-manager/issues/119#issuecomment-13761872.

## 

Pierre GIRAUD
Géomaticien, Analyste

Camptocamp France SAS
Savoie Technolac, BP 352
73377 Le Bourget du Lac, Cedex

Tel : 00 33 4 79 44 44 93
Mail : pierre.giraud@camptocamp.com
http://www.camptocamp.com
