### ISSUE TITLE
Wrong Attribution for OSM

### ISSUE THREAD

**Issue by wonderchook** [hotosm/osm-tasking-manager#123]
Interface still showing the old attribution as CC-BY-SA, this should be switched to the new "© OpenStreetMap contributors"

**Comment by monkz** [comment]
Updating OpenLayers should be sufficient
EDIT:
it's only in OL dev version

**Comment by EdLoach** [comment]
I'm not an Openlayers expert, but think the attribution can be specified for the .osm layer in job.js and in resetMap in job.new.js (in https://github.com/hotosm/osm-tasking-manager/tree/master/OSMTM/static/js folder)

**Comment by neogeomat** [comment]
The Latest version of Openlayers 2.12 still shows CC-By-SA

**Comment by EdLoach** [comment]
Yes, but http://dev.openlayers.org/docs/files/OpenLayers/Layer/OSM-js.html suggests the OSM layer constructor allows you to specify options (inherited from layer) which I think means the attribution can be whatever is specified, rather than whatever the default is. I've not tried it though.

**Comment by pgiraud** [comment]
This should be really easy to fix. I postponed this one, but I can fix it quickly if this is important. Is it?

**Comment by pgiraud** [comment]
Fixed.

**Comment by EdLoach** [comment]
Thanks. I was still typing a reply here as the "Fixed" bit suddenly appeared above.
