### ISSUE TITLE
ability to directly link to task square

### ISSUE THREAD

**Issue by awright** [hotosm/osm-tasking-manager#127]
would be great to be able to identify task square with a direct link. for example:

http://tasks.hotosm.org/job/190/task/x/y

two advantages would be for reference when looking for help and the ability to return to the same task square if left incomplete.  

can't add labels, but this is obviously a feature request.

**Comment by pgiraud** [comment]
Hi @awright, this is something I have already done in the `workflow` branch. This work is still in progress though. Actually quite stopped at the moment.

**Comment by pgiraud** [comment]
Fixed.
