### ISSUE TITLE
Option to use iD editor

### ISSUE THREAD

**Issue by maning** [hotosm/osm-tasking-manager#128]
Since it is added in the main OSM website, an option to use iD would be great as well.

**Comment by snkashis** [comment]
Hey @maning, I have a branch up for this https://github.com/snkashis/osm-tasking-manager/tree/id_editing, PR submitted, but you might have some ideas for additions to it.

**Comment by pgiraud** [comment]
Pull request merged. Thanks a lot @snkashis.

**Comment by mikelmaron** [comment]
Reopening. Need to add imagery link, if there are tiles

**Comment by wonderchook** [comment]
looks like this is finished.
