### ISSUE TITLE
Mannually configuring tms imagery url

### ISSUE THREAD

**Issue by neogeomat** [hotosm/osm-tasking-manager#131]
The imagery url I am using is 
http://hiu-maps.net/hot/1.0.0/kathmandu_flipped/{zoom}/{x}/{y}.png (1st link)

On clicking Imagery link in Tasking Manager, it requests this url 
http://127.0.0.1:8111/imagery?title=Kathmandu%20Valley,%20Nepal%20%E2%80%93%20Mapping%20for%20an%20earthquake%20risk%20assessment&**type=htt**&url=http://hiu-maps.net/hot/1.0.0/kathmandu_flipped/{zoom}/{x}/{y}.png (2nd)

this activates the imagery layer in JOSM, but it gives red tiles

The imagery providers have suggested to use this link instead
http://127.0.0.1:8111/imagery?title=Kathmandu%20Valley,%20Nepal%20%E2%80%93%20Mapping%20for%20an%20earthquake%20risk%20assessment&**type=tms**&url=http://hiu-maps.net/hot/1.0.0/kathmandu_flipped/{zoom}/{x}/{y}.png (3rd)

The only difference in the two link is that the  2nd link has type=htt and the 3rd one has type=tms. This type = htt parameter is generated automatically by the tasking manager not by me.

I have checked both the links with browser and the link with type=htt gives red tiles whereas the link with type=tms gives required images. so it is surely a matter of spelling.

Is there any way to generate the 3rd request (not the 2nd) on clicking the imagery text in Tasking Manager?

**Comment by pgiraud** [comment]
The value in the url field should look like the following : "tms[22]:http://hiu-maps.net/hot/1.0.0/kathmandu_flipped/{zoom}/{x}/{y}.png"
Note the use of the "tms[xx]" prefix.

I leave this issue open since it should be documented.

**Comment by neogeomat** [comment]
Thank you very much, it saves lot of time in mapping parties
