### ISSUE TITLE
production.ini

### ISSUE THREAD

**Issue by oeon** [hotosm/osm-tasking-manager#138]
I needed to add `fanstatic.base_url = https://example.com/myapp` in production.ini on a recent setup. I have another osm-tasking-manager running with a URL scheme like the Original (tasks.hotosm.org) and it doesn't require it though. Maybe we should document?

**Comment by pgiraud** [comment]
I decided to get rid of fanstatic for now. Css minified file is to be built by hand now.
Closing.
