### ISSUE TITLE
Names of users

### ISSUE THREAD

**Issue by jeffhaack** [hotosm/osm-tasking-manager#143]
Hey guys, just thought I'd mention a couple things I've noticed while teaching the Tasking Manager to newbies in Sri Lanka.  Feature requests really.

One is just a Ux thing.  The "Take a task" button confuses people a lot, because they invariably think they should click on this button and then choose a square, which leads to chaos.  I don't think it's clear that these are the two options and one of them is random.

Second is when a user selects a square it gets assigned to them, but if they then move the map they forget which square was theirs.  It would be nice to color code the square for the specific user so they know which is theirs.

And in the same vein, it would be even nicer to see which user has which square, but that is probably less of a priority.

Cheers,
Jeff

**Comment by pgiraud** [comment]
Thanks a lot for those User Experience feedbacks and proposals.
I think this is the worse part of the tasking manager currently (with the
"create your instance" documentation actually).
I'm looking forward to improving this.

On Wed, Aug 14, 2013 at 4:27 PM, jeffhaack notifications@github.com wrote:

> Hey guys, just thought I'd mention a couple things I've noticed while
> teaching the Tasking Manager to newbies in Sri Lanka. Feature requests
> really.
> 
> One is just a Ux thing. The "Take a task" button confuses people a lot,
> because they invariably think they should click on this button and then
> choose a square, which leads to chaos. I don't think it's clear that these
> are the two options and one of them is random.
> 
> Second is when a user selects a square it gets assigned to them, but if
> they then move the map they forget which square was theirs. It would be
> nice to color code the square for the specific user so they know which is
> theirs.
> 
> And in the same vein, it would be even nicer to see which user has which
> square, but that is probably less of a priority.
> 
> Cheers,
> Jeff
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/hotosm/osm-tasking-manager/issues/143
> .

## 

Pierre GIRAUD
Géomaticien, Analyste

Camptocamp France SAS
Savoie Technolac, BP 352
73377 Le Bourget du Lac, Cedex

Tel : 00 33 4 79 44 44 93
Mail : pierre.giraud@camptocamp.com
http://www.camptocamp.com

**Comment by pgiraud** [comment]
Improved in the `workflow` branch.

**Comment by pgiraud** [comment]
Workflow branch merged. Closing.
