### ISSUE TITLE
Specify which version of fanstatic to install

### ISSUE THREAD

**Issue by MateoV** [hotosm/osm-tasking-manager#144]
Running setup installed version 1.0a3 of fanstatic. This version does not contain the `render_topbottom_into_html()` method that is being called in the pyramid_fanstatic `__init__.py`. `fanstatic.debug` and `fanstatic.bottom` in the .ini also give errors.

Had to revert to v0.16 and all is well. I would do this myself but I am not familiar with how the package is being installed.

**Comment by pgiraud** [comment]
You can put `'fanstatic==0.16'` in the `setup.py` config file.
I have been trying myself this morning, but it looks like I have a lot of troubles.

**Comment by pgiraud** [comment]
@MateoV I decided to get rid of fanstatic for now. It's probably a bit more painful for development but you now have to execute less in the shell if you change the styles. See `README.rst`.
