### ISSUE TITLE
"Mark task as done" button does nothing

### ISSUE THREAD

**Issue by danstowell** [hotosm/osm-tasking-manager#151]
This is a very fundamental problem so I hope it's just me...

Working on http://tasks.hotosm.org/job/303 I took a square, edited it in JOSM for about 20 minutes, then went back to the website to click on "Mark task as done". The webpage does nothing. It doesn't appear to be waiting for the next page to load or anything, just no reaction. (So not marked as done.)

It doesn't seem to matter if I type anything in the Comment box or not.

In the javascript console when I click on the button I get the following warning:

```
Timestamp: 31/08/13 17:28:57
Warning: Empty string passed to getElementById().
Source File: http://tasks.hotosm.org/static/js/lib/jquery-1.7.1.min.js
Line: 2
```

I'm on Ubuntu 13.04, Firefox 23.0, no weird FF plugins.

I had previously refreshed that page once or twice. I don't know if that's allowed or not.

The edits I made are in changeset http://www.openstreetmap.org/browse/changeset/17605983

**Comment by pgiraud** [comment]
The problem was due to a not correctly closed html tag in the extra instructions.
