### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by dichapabe** [hotosm/osm-tasking-manager#152]
Handling server error while accessing on Job 306 (http://tasks.hotosm.org/job/306) using firefox and chrome.

**Comment by maning** [comment]
Adding more info.

This job was configured as private but after adding @dichapabe in the whitelist, the "500 Internal Server Error" still occur.

**Comment by dichapabe** [comment]
Error solved through clearing cache and deleting cookies.
