### ISSUE TITLE
Use HOT style as default background

### ISSUE THREAD

**Issue by yohanboniface** [hotosm/osm-tasking-manager#167]
As discussed in IRC just now, it can make sense to use the HOT style as default background :)

Here is the URL scheme: http://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png

Thanks :)

**Comment by pierzen** [comment]
I vote for this too. 

 
Pierre 

---

 De : Yohan Boniface notifications@github.com
À : hotosm/osm-tasking-manager osm-tasking-manager@noreply.github.com 
Envoyé le : Jeudi 21 novembre 2013 13h31
Objet : [osm-tasking-manager] Use HOT style as default background (#167)

As discussed in IRC just now, it can make sense to use the HOT style as default background :)
Here is the URL scheme: http://{s}.tile.openstreetmap.fr/hot/{z}/{x}/{y}.png
Thanks :)
