### ISSUE TITLE
deep-linking to a task that doesn't exist can leave GUI in confused state [workflow branch]

### ISSUE THREAD

**Issue by danstowell** [hotosm/osm-tasking-manager#174]
If you're already looking at the task-manager and then you paste a URL into your URL bar, for a task that might exist but doesn't, such as this one:

http://tasks2.hotosm.org/job/1002#task/860/543/10

...the HTML in the page doesn't update. So if I already am looking at some job with "Locked... Marked as done..." data listed down the left-hand side, and then I go to that URL, it _appears_ as though the "Locked... Marked as done..." info relates to this URL, whereas in reality it's "stale".

The URL I give above is meaningful, but it relates to a square that has since been split up into four smaller squares.

I'd suggest that if the URL requests a task that isn't live in the database, the TM Task pane should at least go back to the default "Take a task" view.

> (It would be extra-cute if it would zoom to the requested area, even without highlighting the tile. This way, URL links would not become invalid just because people have split tasks up.)

**Comment by pgiraud** [comment]
Thanks for this detailed report.
