### ISSUE TITLE
make task boundary visible in iD

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/osm-tasking-manager#175]
either these instructions listed directly in tasking manager, or a fix to edit link to load that GPX file automatically when opening iD

"After I select a tile and open the ID editor, the boundaries of my selected tile are no longer visible?"

for iD, they need to download the .gpx file for the given tile
then drop it in iD
the tile should appear as a new gpx layer

**Comment by skorasaurus** [comment]
a huge +1 to this. This was one of the dealbreakers to using iD when I was in Cap-Haitien earlier this year with our mappers.

**Comment by pierzen** [comment]
To have the capacity to bring less experienced people to participate to activation, we need that such operations be simple as a click.

I agree that this is an important feature. Some coordination has to be made with ID developpers to see what is the best solution to implement this.

Is it possible to add parameters to the ID call. thus asking to trace a background polygon?  Would it be better if this is done this way?

**Comment by pgiraud** [comment]
My bad. Ball is in my hands.
https://github.com/openstreetmap/iD/issues/1965#issuecomment-29245516

**Comment by mikelmaron** [comment]
so just need to craft the url, right? great stuff @pgiraud and id developers, like magic!

**Comment by pgiraud** [comment]
Fixed via https://github.com/hotosm/osm-tasking-manager/commit/2c206a6f9ea8bbc829d8ad017f0d10fb083e6dcb

**Comment by skorasaurus** [comment]
hoorah, thank you, merci beaucoup!

**Comment by pierzen** [comment]
Yes nice and simple. Merci Pierre.
