### ISSUE TITLE
popups are not sticky

### ISSUE THREAD

**Issue by mvexel** [hotosm/osm-tasking-manager#18]
in the individual task screen, there's a popup window for the workflow that contains among other things the URL to be pasted in JOSM / Potlatch. These pop up on mouse over but disappear when the pointer moves away from the link, making it impossible to select and copy the link.

As this will be a crucial part of many tasks I think this should not be in a popup but as a step on screen.

**Comment by pgiraud** [comment]
With the new layout, this issue can be considered as fixed.
