### ISSUE TITLE
Improve "show user tiles on map" performance

### ISSUE THREAD

**Issue by pgiraud** [hotosm/osm-tasking-manager#189]

**Comment by harry-wood** [comment]
This was raised in relation to this job http://tasks.hotosm.org/job/425      One solution would be to say that job shouldn't have that many task squares! It seems like too many. What's the current maximum?

**Comment by pgiraud** [comment]
There's no limitation currently. It's job's author to pay enough attention to this.

**Comment by pierzen** [comment]
About the firts step of Job creation, where we define the zone and the zoom level, It would be useful to have the abitlity to edit and revise these. Even if the job is saved, if no work is done yet,the editor coud have the possibility to revise.

This way, we could first indicate the job as private, sometime discuss with others. I do myself this using the dev server, and suggest others to proceed this way.  But it would be surely useful to integrate this functionality into the Task Manager.
