### ISSUE TITLE
what constitutes a validated tile?

### ISSUE THREAD

**Issue by mvexel** [hotosm/osm-tasking-manager#19]
There should be some instruction for experienced mappers on how to validate. What constitutes a good tile? This would probably vary by task group.

**Comment by wonderchook** [comment]
I added this to the feature requests: https://github.com/pgiraud/OSMTM/wiki/Feature-Requests

Seems sensible for me.

**Comment by wonderchook** [comment]
I'm closing this, because it has been added to the feature request.  Thanks for the input Martijn!
