### ISSUE TITLE
Highlighting finished tiles based on timestamp from the stats tab.

### ISSUE THREAD

**Issue by AndrewBuck** [hotosm/osm-tasking-manager#199]
Right now you can mouse over peoples names to see what tiles were done by them.  It would also be really nice to have the same mouse over type functionality on the 'stats' tab so as you drag your mouse along the line it also shows what tiles had been done up to that point.

**Comment by dodobas** [comment]
You can see this in action http://tasks.dev.hotosm.org/job/450
