### ISSUE TITLE
Taking an "Advanced Mapper" Task When None are Available Leads to Error

### ISSUE THREAD

**Issue by wonderchook** [hotosm/osm-tasking-manager#2]
I was working on the Padang task: http://tasks.hotosm.org/job/2 and tried to take a new task.

I am getting an error, I believe this is because there are no more advanced tasks available.  I think it should default to giving me a beginner mapping task.

**Comment by pgiraud** [comment]
In commit 14a551b0d88d3fa72850248e1e84c7b4d7c43f1f, I'm showing a error when no task is available for current user.
Does it match your needs?
