### ISSUE TITLE
Invalidate / Comments info lost if later split the job

### ISSUE THREAD

**Issue by pierzen** [hotosm/osm-tasking-manager#200]
I first invalidated a job where a lot of mapping had to be done. I added comments to specify what was still to be done. Then I split the job. Verification showed that comment is lost after the split.

See http://tasks.hotosm.org/job/447#task/15842/17847/15

**Comment by dodobas** [comment]
So, you added a comment on Task invalidation, and expect to see that comment as as a part of history on every new splinted tile?

**Comment by severinmenard** [comment]
Yes, would be great

**Comment by pierzen** [comment]
Yes, even if the tile is split later, this history should be kept after the split.

**Comment by dodobas** [comment]
You can test it on the test server, however, the implementation is a bit hackish, we clone project history reference it on the new tile. We also use negative version numbers as a filter to exclude _cloned_ history items from stats

Everything else would probably require too much time

**Comment by pierzen** [comment]
Test invalidating / spliting and completing a task worked well. see http://tasks.dev.hotosm.org/job/447#task/15845/17842/15
Comments of various steps is kept in the tile after split.

Thands dodobas
