### ISSUE TITLE
Need Grid Lines

### ISSUE THREAD

**Issue by net127** [hotosm/osm-tasking-manager#221]
It is very difficult to quickly analyze a large amount of low-contrast satellite images at a high zoom level without grid lines.

Please consider adding grid lines. Please consider making their spacing settable. It would really speed things up. I wouldn't be looking at some areas multiple times while (possibly) missing others.

thanks,
glenn

**Comment by pgiraud** [comment]
I'm afraid this is not a Tasking Manager issue. Satellite images are not displayed in the Tasking Manager itself. They are displayed on the editor you chose (ie. idEditor or JOSM).
Please report this issue to the appropriate project development team.

**Comment by net127** [comment]
Agreed. I have opened an issue with the iD team:
https://github.com/openstreetmap/iD/issues/2186
