### ISSUE TITLE
In home.mako, Publish alt title is "Archive the job"

### ISSUE THREAD

**Issue by arno974** [hotosm/osm-tasking-manager#222]
Hey Guys,

Minor error, in the home.mako template the title of the publish action is "Archive the job" instead of "Publish the job":
https://github.com/hotosm/osm-tasking-manager/blob/master/OSMTM/templates/home.mako#L103

A.

**Comment by pgiraud** [comment]
Fixed with 6a691777638743b79e2ff2ff2cf9dcb3d0df0f1a. Thanks @arno974
