### ISSUE TITLE
When clicking "Validate" it asks for a comment about why invalid

### ISSUE THREAD

**Issue by danstowell** [hotosm/osm-tasking-manager#223]
Currently I'm working on http://tasks.hotosm.org/job/489

I clicked "Validate", i.e. to mark a tile as correct. Iit asks for a comment about why invalid, i.e. the text was wrong, the text seemed to think the tile was incorrect. The tile was still marked green, so it's just the text that's wrong.

**Comment by pgiraud** [comment]
Duplicate #217.
