### ISSUE TITLE
Error message when trying to upload kmls to create tasks

### ISSUE THREAD

**Issue by pedrito1414** [hotosm/osm-tasking-manager#247]
Hi, I have been producing kmls for Missing Maps tasks and uploading them to create tasks in the TM.

Sometimes it works, but often I upload the file and then choose the tile layout and then hit Create project and it jumps back to Step 1 screen and says:

"Sorry, could not create the project.
(IntegrityError) new row for relation "areas" violates check constraint "enforce_dims_geometry""

The kmls were created in google earth from polygons.

**Comment by pgiraud** [comment]
This is unfortunately due to a known issue.
https://github.com/hotosm/osm-tasking-manager2/issues/334

Duplicate. Closing.

**Comment by pedrito1414** [comment]
Thanks Pierre.

Pete

**Comment by pgiraud** [comment]
@pedrito1414 if you still need to create areas using your KMLs you can try to downsample them manually.

**Comment by pedrito1414** [comment]
@pgiraud downloaded qgis and found another way... Thanks, though...
