### ISSUE TITLE
Mark Invalidated Tasks with a Different Color

### ISSUE THREAD

**Issue by schnuerle** [hotosm/osm-tasking-manager#249]
Right now, when you invalidate a task, it just goes back to grey.  Maybe it should be yellow so you can see which task have already had data uploaded to OSM, but need work.  

In this case, I would also recommend greying out (but still allowing downloading) of the .osm blue button, since you will likely only need the already imported OSM data to make the fixes requested.

**Comment by schnuerle** [comment]
Wait I now see there is a new version called osm-tasking-manager2 that already has this feature. Sorry.  Maybe rename or make it more apparent in the Read.me?

**Comment by pgiraud** [comment]
@schnuerle there's a big "Deprecated" warning at the top of the README. Do you think we should add something else?

**Comment by schnuerle** [comment]
Lol, I didn't see it, I actually saw the text at the top instead.  Make it flashing and rainbow colors?  Just kidding.  It's fine and I should have seen it, sorry.

**Comment by schnuerle** [comment]
I'm currently using the US Task Manager http://tasks.openstreetmap.us/about and since it links here I assumed this was the most recent and just went right to the issues area.  

Maybe the issue I created should have been to update that server with the latest version 2 of the TM - not sure who to contact about that. Thanks.
