### ISSUE TITLE
Monitoring Task Manager problems via emails notification for quicker admin response

### ISSUE THREAD

**Issue by pierzen** [hotosm/osm-tasking-manager#251]
A simple solution to monitor problems in an application, is to add instructions to send Email notifications to technical people that can quickly fix the problem + to the Administrator.

I suggest that such instructions be added in the TM or the server managing the TM if they can help in situations like the crashes to the TM today.

**Comment by IknowJoseph** [comment]
Do we need a more general HOT monitoring system? I've been involved in some discussion about this before, but possibly offline; I couldn't find anything here or https://github.com/hotosm/hotosm

In my day job we use Nagios to alert technical folks about numerous issues, many of which are simply "this website is not responding". I don't know if Nagios is what we'd want here, but I'd guess there's something similar & suitable.

**Comment by pgiraud** [comment]
As far as I know, @dodobas already uses monitoring tools.

**Comment by pgiraud** [comment]
I will close this issue though since:
- this is the V1 repository,
- this issue is not specifically related to "tasking manager".
