### ISSUE TITLE
automatically load imagery in editors

### ISSUE THREAD

**Issue by pgiraud** [hotosm/osm-tasking-manager#37]
Kate - "not sure if this is possible in Potlatch2 looks like it is in JOSM"

**Comment by fredericbonifas** [comment]
Lokks like it is possible in Potlatch2, e.g. http://www.openstreetmap.org/edit?lat=51.745989&lon=13.951828&zoom=20&tileurl=http://wms.openstreetmap.de/tms/Calau/!/!/!.png

**Comment by jsanz** [comment]
Looking at the [imagery links](http://wiki.openstreetmap.org/wiki/Typhoon_Haiyan#Potential_Imagery) at the wiki it's possible for JOSM and iD. It would be nice to revisit this feature request :)

**Comment by mikelmaron** [comment]
This may be addressed for iD in https://github.com/hotosm/osm-tasking-manager/pull/178
And for JOSM, it's implemented, just takes a second click ... right?

**Comment by jsanz** [comment]
It's implemented on the tasking manger connecting with remote server of JOSM, this issue can be closed AFAIK

**Comment by mikelmaron** [comment]
great. and we can close on iD with https://github.com/hotosm/osm-tasking-manager/pull/179
