### ISSUE TITLE
Cancel own task when accidentally pressed done?

### ISSUE THREAD

**Issue by jywarren** [hotosm/osm-tasking-manager#4]
http://tasks.hotosm.org/job/2/task/51046/32591

i did this with the above. Maybe the validation stage will catch it but given that you have user accounts it seems not unreasonable.

**Comment by pgiraud** [comment]
Thanks for this report. I just invalidated the task.
It looks like we need something in the application to allow users undo mistaken behavior. Your feedback helps us a lot.

**Comment by pgiraud** [comment]
Users can now invalidate a validated task.
