### ISSUE TITLE
Tasking server time out

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-tasking-manager#46]
Hi,

I fully understand the need of a time out for the tasking server, but when the tiles ask for several hours to be finished, the mapper may want to do it in several times. If I understood well, when the time is out, the mapper has to pass through the whole process again and if she/he does not remember the location of her/his tile, can feel disappointed to have to start a new one. 
Could it be possible to propose a bookmark or whatever allowing the mapper to get directly to the page that gives the possibility to lock the tile ?

Best,

Severin

**Comment by pgiraud** [comment]
Thanks for this report.
Can you give more hint on what you would exactly do with this link?

What if there was a link to add extra time to a tile when the user knows that he doesn't have enough time left?
Or what if the user would be proposed to re-take a tile he previously took but got expired? In this case, we cannot prevent an other user to take the tile.

**Comment by severinmenard** [comment]
Yes, no problem if another people took it, but in my own example, I started
a Padang tile idowntown that needs 4 or 5 hours to be completed due ton the
very numerous buildings. I wanted to do it in several times. Tell me if I
am wrong, but when I tried to connect the second time, it was not possible
to go directly to the page allowing to lock the tile, but I had to select
it in the general map again. This is this step that I suggested to change
cause people can forget the exact location of their ongoing tile
Extra time is good but not for my case : I wanted to map I would say one
jour a day. On Padang, the contributions are few so very likely nobody
would have completed the tile I was digitizing.
The second case you describe is exactly what I am talking to. And no prob
if someone would have completed the tile in the meantime, of course.

On Fri, Jan 27, 2012 at 12:48 PM, Pierre GIRAUD <
reply@reply.github.com

**Comment by wonderchook** [comment]
I think the best solution would be a way to checkout a square from the URL.  That doesn't prevent a user from taking the square, but it does allow someone to go back to work in the same area.

**Comment by severinmenard** [comment]
I fully agree

On Mon, Feb 6, 2012 at 2:37 PM, Kate Chapman <
reply@reply.github.com

**Comment by pgiraud** [comment]
Now, there's a "take it again" link which allows you to "re-take" a task which have been unlocked (automatically or manually).
Then, can we considered this issue as fixed?

**Comment by severinmenard** [comment]
Just tested it and seems good. How does it work ? It proposes the last
taken task whenever it was ? And if  it has been marked as done or
validated in the meantime ?

On Sat, Feb 25, 2012 at 3:20 AM, Pierre GIRAUD <
reply@reply.github.com

**Comment by pgiraud** [comment]
Yes, it proposes the last taken task.
If it as been "taken", "marked as done", or "validated", you won't be
proposed to take it again.
If you didn't reload the page and you see the "take it again" link
then you'll be sent an error message.

I just gave it a try using a second user account and it seems to work
perfectly well.

On Sat, Feb 25, 2012 at 2:06 PM, severinmenard
reply@reply.github.com
wrote:

> Just tested it and seems good. How does it work ? It proposes the last
> taken task whenever it was ? And if  it has been marked as done or
> validated in the meantime ?
> 
> On Sat, Feb 25, 2012 at 3:20 AM, Pierre GIRAUD <
> reply@reply.github.com
> 
> > wrote:
> > 
> > Now, there's a "take it again" link which allows you to "re-take" a task
> > which have been unlocked (automatically or manually).
> > Then, can we considered this issue as fixed?
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/pgiraud/OSMTM/issues/46#issuecomment-4171437
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pgiraud/OSMTM/issues/46#issuecomment-4172726

## 

Pierre GIRAUD
Géomaticien, Analyste

Camptocamp France SAS
Savoie Technolac, BP 352
73377 Le Bourget du Lac, Cedex

Tel : 00 33 4 79 44 44 93
Mail : pierre.giraud@camptocamp.com
http://www.camptocamp.com
