### ISSUE TITLE
Divide Tasks into Categories

### ISSUE THREAD

**Issue by wonderchook** [hotosm/osm-tasking-manager#47]
Now that there are a lot of tasks it would be good to have a way to divide them into categories.

Maybe tagging?  That way instead of just linking to the front page you could link to a specific category.

For example right now there are multiple tasks in Haiti and multiple ones in Walikale this could be divided up, so people could link to a specific "region" or "type" of tasks.

I'm up for other suggestions, just trying to think through how to get the long list under control

**Comment by pgiraud** [comment]
I added a tag manager for jobs. Let me know if it answers your request or not.

**Comment by wonderchook** [comment]
Cool! That does it for me.
