### ISSUE TITLE
Unvalidate green validated squares

### ISSUE THREAD

**Issue by severinmenard** [hotosm/osm-tasking-manager#55]
Is there a way to do this ? Some squares have been green validated too quickly in our job for the Saint-Marc, Haiti mapping (http://tasks.hotosm.org/job/26)

**Comment by pgiraud** [comment]
Duplicate of #53.

**Comment by severinmenard** [comment]
en effet, dsol. C'est donc pass en feature request ?

On Fri, Apr 13, 2012 at 12:43 PM, Pierre GIRAUD <
reply@reply.github.com

**Comment by pgiraud** [comment]
C'est Kate qui avait exprimé ce besoin il y a quelques temps. Je n'ai pas pris le temps d'en tenir compte encore.
Je vais voir ce que je peux faire ce week-end.

Cette notion de validation ne me parait pas idéale. Je trouve qu'on laisse un accès trop facile à la validation des tuiles. Pour moi, la validation ne devrait être faite que par les admins, ou en tous cas, une liste prédéfinie de validateurs.

**Comment by severinmenard** [comment]
oui

 http://img4.hostingpics.net/pics/224326500pxHotlogowithtext.png
- Severin MENARD
  France tel (+33) 9 70 46 75 95
  Brasil tel (+55) 71 33 44 55 71
  Skype ID severin.menard
  *
- *
  2012/4/13 Pierre GIRAUD <
  reply@reply.github.com
