### ISSUE TITLE
Way to Organize the Front Page

### ISSUE THREAD

**Issue by wonderchook** [hotosm/osm-tasking-manager#58]
The tags have done a lot to make it easier to sort tasks.  It would be great if there was a way to create an organized front page. I was thinking administrators could create featured tasks by tagging them as such and the would show at the top.  Other tasks could be organized by other types of tags.

The flow of the page would be:

Featured Tasks

Link to country/region specific tasks with description 1

Link to country/region specific tasks with description 2

**Comment by pgiraud** [comment]
Hi Kate.

Can you please go to http://tasks-dev.hotosm.org/ and share your thoughts?

Thanks

**Comment by pgiraud** [comment]
I'm closing this issue since the homepage has changed. @wonderchook, please tell me if it is still not what you envisionned.
