### ISSUE TITLE
load new imagery layer into JOSM

### ISSUE THREAD

**Issue by wonderchook** [hotosm/osm-tasking-manager#63]
The JOSM remote control allows loading of new imagery layers. Can we make it so if a URL is in the imagery text box that it will be added automatically.

**Comment by pgiraud** [comment]
Please review #65.

**Comment by mikelmaron** [comment]
what about potlatch and other editors?

**Comment by pgiraud** [comment]
I would be happy to do it for potlatch as well if this is supported. Please point me to documentation if you find some.

**Comment by wonderchook** [comment]
I didn't find support for the other editors, so I didn't request it.

**Comment by mikelmaron** [comment]
sorry, wishful thinking. you can close issue. might be worth raising on potlatch-dev?
