### ISSUE TITLE
Confusing instruction when opening in Potlatch2

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/osm-tasking-manager#68]
Open area in potlatch2. This is too polite. It's confusing why the vector file is necessary.
"Please consider adding the tasks extent as a new vector file using the following url:"

Maybe makes more sense at the bottom of dialogue, with a little more explanation

**Comment by pgiraud** [comment]
This may deserve a specific explanation somewhere else.
As far as the dialog doesn't exist anymore, I suggest we close this issue.
