### ISSUE TITLE
After accepting Nextview, sent to a unstyled page

### ISSUE THREAD

**Issue by mikelmaron** [hotosm/osm-tasking-manager#69]
for example,  http://tasks.hotosm.org/job/40/task/40110/32792

**Comment by pgiraud** [comment]
Can you give more context please?
How did you get this link?

On Wed, May 23, 2012 at 7:59 AM, Mikel Maron
reply@reply.github.com
wrote:

**Comment by wonderchook** [comment]
I'm not having this issue. Can you give more context Mikel? e.g. browser, OS, etc?

**Comment by mikelmaron** [comment]
- Select a Task
- Go to "Task tab"
- "Take a Task"
- "review and acknowledge" NextView license agreement
- "I agree" or "No thanks" redirects back to something like http://tasks.hotosm.org/job/40/task/40109/32791, which is not styled

I'm using Chrome on Ubuntu

If you have already accepted NextView, you can switch it off again http://tasks.hotosm.org/profile/nextview

**Comment by pgiraud** [comment]
Now I see exactly what you mean. Actually the page is not complete. It corresponds to the "task tab contain" of the job's page.
Thanks for the report.

**Comment by pgiraud** [comment]
Fixed.
