### ISSUE TITLE
No Button to Make New Tasks

### ISSUE THREAD

**Issue by wonderchook** [hotosm/osm-tasking-manager#77]
The new update to the Tasking Manager is great! Except I can't find the button to make a new task.

**Comment by pgiraud** [comment]
You're right. This is something that I forgot to re-add.
For now, you can add a new job by using the following url:
http://tasks.hotosm.org/job/new

On Fri, Aug 3, 2012 at 11:06 AM, Kate Chapman
reply@reply.github.com
wrote:

> The new update to the Tasking Manager is great! Except I can't find the button to make a new task.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/pgiraud/OSMTM/issues/77

## 

Pierre GIRAUD
Géomaticien, Analyste

Camptocamp France SAS
Savoie Technolac, BP 352
73377 Le Bourget du Lac, Cedex

Tel : 00 33 4 79 44 44 93
Mail : pierre.giraud@camptocamp.com
http://www.camptocamp.com

**Comment by mikelmaron** [comment]
Also, no link to edit an existing job

**Comment by pgiraud** [comment]
Fixed with bab31b05628602a7701410c5c91099313e819f06

**Comment by pgiraud** [comment]
@mikelmaron The links to edit / delete / mark as archived are available in the home page when admin user mouseovers a job.
Do you think that it would be worth adding those links in each job's page as well?

**Comment by mikelmaron** [comment]
Yes @pgiraud, found those links later on.

I think it is sensible to have the link on each job's page, but not high priority if it's a big issue, since we can find them on the front page easy enough.
