### ISSUE TITLE
Mark the export.osm bbox file as upload=false

### ISSUE THREAD

**Issue by AndrewBuck** [hotosm/osm-tasking-manager#80]
The export.osm file available for download on each job task does not have the upload=false tag set in the osm tag header.  Setting this would trigger a warning in josm if the user tries to upload this bbox into the osm DB.  An example of what the opening xml tag in the file should look like to enable this feature is given below.

`<osm version="0.6" upload="false">`

**Comment by pgiraud** [comment]
@AndrewBuck Can you confirm that this is fixed?

**Comment by AndrewBuck** [comment]
Yes, this is fixed now (as you probably already checked).  Thank you.  I didn't see you 'please confirm' comment until now.
