### ISSUE TITLE
tests: document how to setup and how to run

### ISSUE THREAD

**Issue by springmeyer** [hotosm/osm-tasking-manager#96]
Setting up OSMTM for the first time I ran into two issues:

1) The README does not indicate if tests exist or how to run them.

2) While tests exist they appear to need setup which is not documented (or I am doing something wrong ). The first run I saw a cascading failure because of `admin_user` not being defined. And then the second run I saw: https://gist.github.com/3893235

For 1), this could be added to the main READ:

``` diff
diff --git a/README.rst b/README.rst
index 44246bf..3d93223 100644
--- a/README.rst
+++ b/README.rst
@@ -53,6 +53,14 @@ Edit the development.ini file and change the ``admin_user`` v your OSM username. 


+Run Tests
+---------
+
+To ensure your build is working properly run the tests::
+
+    python setup.py test
+
+
 Run OSMTM
 ---------

```

For 2) could you provide docs on the proper way to setup and run the tests?

**Comment by springmeyer** [comment]
As, just realized one of my errors in guessing how to run the tests. Second time I ran I forgot to enter the virtual env. Anyway, this is first set of errors that obviously result from not properly setting up my configuration: https://gist.github.com/3893312. Again, can you please add docs so that new developers do not have to guess how to setup and run tests?

**Comment by pgiraud** [comment]
Please note that the tests are currently broken (and incomplete).
I have a "tests" branch in which I started fixing them.
